#!/usr/bin/python

# Copyright (C) 2011-2015 Florian Bruckner
#
# This file is part of magnum.msh.
#
# magnum.msh is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# magnum.msh is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with magnum.msh. If not, see <http://www.gnu.org/licenses/>.
#
# Last modified by Florian Bruckner, 2015-10-14

import argparse
from dolfin import *
from magnummsh import *

if __name__ == "__main__":
  parser = argparse.ArgumentParser(prog='inp2magnum')
  parser.add_argument('-d', '--domains', help='Output file for domain information')
  parser.add_argument('-f', '--field', help='Output file for extracted data')
  parser.add_argument('source', help='Input INP file')
  parser.add_argument('target', help='Output mesh file(\'.pvd\', \'.xml\')')
  args = parser.parse_args()

  converter = INPReader(args.source)
  File(args.target) << converter.mesh()
  if args.domains:
    File(args.domains) << converter.domains()
  if args.field:
    File(args.field) << converter.data()
  converter.print_stats()
