#!/usr/bin/python

# Copyright (C) 2011-2015 Florian Bruckner
#
# This file is part of magnum.msh.
#
# magnum.msh is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# magnum.msh is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with magnum.msh. If not, see <http://www.gnu.org/licenses/>.
#
# Last modified by Florian Bruckner, 2015-10-13

import argparse
from magnummsh import *

if __name__ == "__main__":
  parser = argparse.ArgumentParser(prog='magnum2inp')
  parser.add_argument('-f', '--field', help='Input file for additional vector data')
  parser.add_argument('source', help='Input XML file')
  parser.add_argument('target', help='Output INP file')
  args = parser.parse_args()

  mesh = Mesh(args.source)
  if args.field is not None:
    VV = VectorFunctionSpace(mesh, "CG", 1)
    field = Function(VV, fieldfile)

  writer = INPWriter(mesh, args.field)
  # TODO: implement read_data(field_file)
  writer.write_inp(args.target)
  writer.print_stats()
